
'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Data.EntityClient
Imports System.ComponentModel
Imports System.Xml.Serialization
Imports System.Runtime.Serialization

<Assembly: EdmSchemaAttribute("0c694d94-72f4-4d9e-95bf-8b4cdc702ced")>

#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("BooksAndAuthors", "PersonAddress", "Person", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Person), "Address", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Address))>
<Assembly: EdmRelationshipAttribute("BooksAndAuthors", "PersonBook", "Person", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Person), "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Book))>
<Assembly: EdmRelationshipAttribute("BooksAndAuthors", "TranslatorLanguages", "Translator", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Translator), "Languages", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Language))>
<Assembly: EdmRelationshipAttribute("BooksAndAuthors", "BookSales", "Book", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Book), "Sales", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SaleByMonth))>
#End Region

#Region "Contexts"
''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class BooksAndAuthorsContainer 
    Inherits ObjectContext

    #Region "Constructors"
    ''' <summary>
    ''' Initializes a new BooksAndAuthorsContainer object using the connection string found in the 'BooksAndAuthorsContainer' section of the application configuration file.
    ''' </summary>
    Public Sub New() 
        MyBase.New("name=BooksAndAuthorsContainer", "BooksAndAuthorsContainer")
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new BooksAndAuthorsContainer object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "BooksAndAuthorsContainer")
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new BooksAndAuthorsContainer object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "BooksAndAuthorsContainer")
        OnContextCreated()
    End Sub
    #End Region
    
    #Region "Partial Methods"
    Partial Private Sub OnContextCreated()
    End Sub
    #End Region
    
    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Books() As ObjectSet(Of Book)
        Get
            If (_Books Is Nothing) Then
                _Books = MyBase.CreateObjectSet(Of Book)("Books")
            End If
            Return _Books
        End Get
    End Property
    
    Private _Books As ObjectSet(Of Book)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Persons() As ObjectSet(Of Person)
        Get
            If (_Persons Is Nothing) Then
                _Persons = MyBase.CreateObjectSet(Of Person)("Persons")
            End If
            Return _Persons
        End Get
    End Property
    
    Private _Persons As ObjectSet(Of Person)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Addresses() As ObjectSet(Of Address)
        Get
            If (_Addresses Is Nothing) Then
                _Addresses = MyBase.CreateObjectSet(Of Address)("Addresses")
            End If
            Return _Addresses
        End Get
    End Property
    
    Private _Addresses As ObjectSet(Of Address)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Languages() As ObjectSet(Of Language)
        Get
            If (_Languages Is Nothing) Then
                _Languages = MyBase.CreateObjectSet(Of Language)("Languages")
            End If
            Return _Languages
        End Get
    End Property
    
    Private _Languages As ObjectSet(Of Language)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property SalesByMonth() As ObjectSet(Of SaleByMonth)
        Get
            If (_SalesByMonth Is Nothing) Then
                _SalesByMonth = MyBase.CreateObjectSet(Of SaleByMonth)("SalesByMonth")
            End If
            Return _SalesByMonth
        End Get
    End Property
    
    Private _SalesByMonth As ObjectSet(Of SaleByMonth)
    #End Region
    #Region "AddTo Methods"
    
    ''' <summary>
    ''' Deprecated Method for adding a new object to the Books EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToBooks(ByVal book As Book)
        MyBase.AddObject("Books", book)
    End Sub
    
    ''' <summary>
    ''' Deprecated Method for adding a new object to the Persons EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToPersons(ByVal person As Person)
        MyBase.AddObject("Persons", person)
    End Sub
    
    ''' <summary>
    ''' Deprecated Method for adding a new object to the Addresses EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToAddresses(ByVal address As Address)
        MyBase.AddObject("Addresses", address)
    End Sub
    
    ''' <summary>
    ''' Deprecated Method for adding a new object to the Languages EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToLanguages(ByVal language As Language)
        MyBase.AddObject("Languages", language)
    End Sub
    
    ''' <summary>
    ''' Deprecated Method for adding a new object to the SalesByMonth EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToSalesByMonth(ByVal saleByMonth As SaleByMonth)
        MyBase.AddObject("SalesByMonth", saleByMonth)
    End Sub
    #End Region
End Class

#End Region
#Region "Entities"
''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="BooksAndAuthors", Name:="Address")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Address 
    Inherits EntityObject
    #Region "Factory Method"
        
    ''' <summary>
    ''' Create a new Address object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="firstLine">Initial value of the FirstLine property.</param>
    ''' <param name="city">Initial value of the City property.</param>
    ''' <param name="postalCode">Initial value of the PostalCode property.</param>
    ''' <param name="state">Initial value of the State property.</param>
    Public Shared Function CreateAddress(id As Global.System.Int32, firstLine As Global.System.String, city As Global.System.String, postalCode As Global.System.Int32, state As Global.System.String) As Address
        Dim address as Address = New Address
        address.Id = id
            
        address.FirstLine = firstLine
            
        address.City = city
            
        address.PostalCode = postalCode
            
        address.State = state
            
        Return address
    End Function
    #End Region
    #Region "Primitive Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (Id <> value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property
    
    Private _Id as Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub
    
    Private Partial Sub OnIdChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FirstLine() As Global.System.String
        Get
            Return _FirstLine
        End Get
        Set
            OnFirstLineChanging(value)
            ReportPropertyChanging("FirstLine")
            _FirstLine = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("FirstLine")
            OnFirstLineChanged()
        End Set
    End Property
    
    Private _FirstLine as Global.System.String
    Private Partial Sub OnFirstLineChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnFirstLineChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SecondLine() As Global.System.String
        Get
            Return _SecondLine
        End Get
        Set
            OnSecondLineChanging(value)
            ReportPropertyChanging("SecondLine")
            _SecondLine = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("SecondLine")
            OnSecondLineChanged()
        End Set
    End Property
    
    Private _SecondLine as Global.System.String
    Private Partial Sub OnSecondLineChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnSecondLineChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property City() As Global.System.String
        Get
            Return _City
        End Get
        Set
            OnCityChanging(value)
            ReportPropertyChanging("City")
            _City = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("City")
            OnCityChanged()
        End Set
    End Property
    
    Private _City as Global.System.String
    Private Partial Sub OnCityChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnCityChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PostalCode() As Global.System.Int32
        Get
            Return _PostalCode
        End Get
        Set
            OnPostalCodeChanging(value)
            ReportPropertyChanging("PostalCode")
            _PostalCode = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PostalCode")
            OnPostalCodeChanged()
        End Set
    End Property
    
    Private _PostalCode as Global.System.Int32
    Private Partial Sub OnPostalCodeChanging(value As Global.System.Int32)
    End Sub
    
    Private Partial Sub OnPostalCodeChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property State() As Global.System.String
        Get
            Return _State
        End Get
        Set
            OnStateChanging(value)
            ReportPropertyChanging("State")
            _State = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("State")
            OnStateChanged()
        End Set
    End Property
    
    Private _State as Global.System.String
    Private Partial Sub OnStateChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnStateChanged()
    End Sub
    
    #End Region
    #Region "Navigation Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BooksAndAuthors", "PersonAddress", "Person")>
    Public Property Person() As Person
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Person)("BooksAndAuthors.PersonAddress", "Person").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Person)("BooksAndAuthors.PersonAddress", "Person").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property PersonReference() As EntityReference(Of Person)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Person)("BooksAndAuthors.PersonAddress", "Person")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Person)("BooksAndAuthors.PersonAddress", "Person", value)
            End If
        End Set
    End Property
    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="BooksAndAuthors", Name:="Author")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Author 
    Inherits Person
    #Region "Factory Method"
        
    ''' <summary>
    ''' Create a new Author object.
    ''' </summary>
    ''' <param name="sSN">Initial value of the SSN property.</param>
    ''' <param name="firstName">Initial value of the FirstName property.</param>
    ''' <param name="lastName">Initial value of the LastName property.</param>
    ''' <param name="phone">Initial value of the Phone property.</param>
    ''' <param name="signed">Initial value of the Signed property.</param>
    Public Shared Function CreateAuthor(sSN As Global.System.String, firstName As Global.System.String, lastName As Global.System.String, phone As PhoneNumber, signed As Global.System.DateTime) As Author
        Dim author as Author = New Author
        author.SSN = sSN
            
        author.FirstName = firstName
            
        author.LastName = lastName
            
        author.Phone = StructuralObject.VerifyComplexObjectIsNotNull(phone, "Phone")
        author.Signed = signed
            
        Return author
    End Function
    #End Region
    #Region "Primitive Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Signed() As Global.System.DateTime
        Get
            Return _Signed
        End Get
        Set
            OnSignedChanging(value)
            ReportPropertyChanging("Signed")
            _Signed = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Signed")
            OnSignedChanged()
        End Set
    End Property
    
    Private _Signed as Global.System.DateTime
    Private Partial Sub OnSignedChanging(value As Global.System.DateTime)
    End Sub
    
    Private Partial Sub OnSignedChanged()
    End Sub
    
    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="BooksAndAuthors", Name:="Book")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Book 
    Inherits EntityObject
    #Region "Factory Method"
        
    ''' <summary>
    ''' Create a new Book object.
    ''' </summary>
    ''' <param name="iSBN">Initial value of the ISBN property.</param>
    ''' <param name="title">Initial value of the Title property.</param>
    ''' <param name="publishingDate">Initial value of the PublishingDate property.</param>
    ''' <param name="pageCount">Initial value of the PageCount property.</param>
    Public Shared Function CreateBook(iSBN As Global.System.String, title As Global.System.String, publishingDate As Global.System.DateTime, pageCount As Global.System.Int32) As Book
        Dim book as Book = New Book
        book.ISBN = iSBN
            
        book.Title = title
            
        book.PublishingDate = publishingDate
            
        book.PageCount = pageCount
            
        Return book
    End Function
    #End Region
    #Region "Primitive Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ISBN() As Global.System.String
        Get
            Return _ISBN
        End Get
        Set
            If (ISBN <> value) Then
                OnISBNChanging(value)
                ReportPropertyChanging("ISBN")
                _ISBN = StructuralObject.SetValidValue(value, False)
                ReportPropertyChanged("ISBN")
                OnISBNChanged()
            End If
        End Set
    End Property
    
    Private _ISBN as Global.System.String
    Private Partial Sub OnISBNChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnISBNChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Title() As Global.System.String
        Get
            Return _Title
        End Get
        Set
            OnTitleChanging(value)
            ReportPropertyChanging("Title")
            _Title = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("Title")
            OnTitleChanged()
        End Set
    End Property
    
    Private _Title as Global.System.String
    Private Partial Sub OnTitleChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnTitleChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PublishingDate() As Global.System.DateTime
        Get
            Return _PublishingDate
        End Get
        Set
            OnPublishingDateChanging(value)
            ReportPropertyChanging("PublishingDate")
            _PublishingDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PublishingDate")
            OnPublishingDateChanged()
        End Set
    End Property
    
    Private _PublishingDate as Global.System.DateTime
    Private Partial Sub OnPublishingDateChanging(value As Global.System.DateTime)
    End Sub
    
    Private Partial Sub OnPublishingDateChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PageCount() As Global.System.Int32
        Get
            Return _PageCount
        End Get
        Set
            OnPageCountChanging(value)
            ReportPropertyChanging("PageCount")
            _PageCount = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PageCount")
            OnPageCountChanged()
        End Set
    End Property
    
    Private _PageCount as Global.System.Int32
    Private Partial Sub OnPageCountChanging(value As Global.System.Int32)
    End Sub
    
    Private Partial Sub OnPageCountChanged()
    End Sub
    
    #End Region
    #Region "Navigation Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BooksAndAuthors", "PersonBook", "Person")>
     Public Property Persons() As EntityCollection(Of Person)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Person)("BooksAndAuthors.PersonBook", "Person")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Person)("BooksAndAuthors.PersonBook", "Person", value)
            End If
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BooksAndAuthors", "BookSales", "Sales")>
     Public Property Sales() As EntityCollection(Of SaleByMonth)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SaleByMonth)("BooksAndAuthors.BookSales", "Sales")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SaleByMonth)("BooksAndAuthors.BookSales", "Sales", value)
            End If
        End Set
    End Property
    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="BooksAndAuthors", Name:="Language")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Language 
    Inherits EntityObject
    #Region "Factory Method"
        
    ''' <summary>
    ''' Create a new Language object.
    ''' </summary>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="name">Initial value of the Name property.</param>
    Public Shared Function CreateLanguage(id As Global.System.Int32, name As Global.System.String) As Language
        Dim language as Language = New Language
        language.Id = id
            
        language.Name = name
            
        Return language
    End Function
    #End Region
    #Region "Primitive Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (Id <> value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property
    
    Private _Id as Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub
    
    Private Partial Sub OnIdChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Name() As Global.System.String
        Get
            Return _Name
        End Get
        Set
            OnNameChanging(value)
            ReportPropertyChanging("Name")
            _Name = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("Name")
            OnNameChanged()
        End Set
    End Property
    
    Private _Name as Global.System.String
    Private Partial Sub OnNameChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnNameChanged()
    End Sub
    
    #End Region
    #Region "Navigation Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BooksAndAuthors", "TranslatorLanguages", "Translator")>
     Public Property Translator() As EntityCollection(Of Translator)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Translator)("BooksAndAuthors.TranslatorLanguages", "Translator")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Translator)("BooksAndAuthors.TranslatorLanguages", "Translator", value)
            End If
        End Set
    End Property
    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="BooksAndAuthors", Name:="Person")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
<KnownTypeAttribute(GetType(Translator))>
<KnownTypeAttribute(GetType(Author))>
Public MustInherit Partial Class Person 
    Inherits EntityObject
    #Region "Primitive Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property SSN() As Global.System.String
        Get
            Return _SSN
        End Get
        Set
            If (SSN <> value) Then
                OnSSNChanging(value)
                ReportPropertyChanging("SSN")
                _SSN = StructuralObject.SetValidValue(value, False)
                ReportPropertyChanged("SSN")
                OnSSNChanged()
            End If
        End Set
    End Property
    
    Private _SSN as Global.System.String
    Private Partial Sub OnSSNChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnSSNChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FirstName() As Global.System.String
        Get
            Return _FirstName
        End Get
        Set
            OnFirstNameChanging(value)
            ReportPropertyChanging("FirstName")
            _FirstName = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("FirstName")
            OnFirstNameChanged()
        End Set
    End Property
    
    Private _FirstName as Global.System.String
    Private Partial Sub OnFirstNameChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnFirstNameChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property LastName() As Global.System.String
        Get
            Return _LastName
        End Get
        Set
            OnLastNameChanging(value)
            ReportPropertyChanging("LastName")
            _LastName = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("LastName")
            OnLastNameChanged()
        End Set
    End Property
    
    Private _LastName as Global.System.String
    Private Partial Sub OnLastNameChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnLastNameChanged()
    End Sub
    
    #End Region
    #Region "Complex Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmComplexPropertyAttribute()>
    <DesignerSerializationVisibility(DesignerSerializationVisibility.Content)>
    <XmlElement(IsNullable:=True)>
    <SoapElement(IsNullable:=True)>
    <DataMemberAttribute()>
    Public Property Phone() As PhoneNumber
        Get
            _Phone = GetValidValue(_Phone, "Phone", False, _PhoneInitialized)
            _PhoneInitialized = True
            Return _Phone
        End Get
        Set
            OnPhoneChanging(value)
            ReportPropertyChanging("Phone")
            _Phone = SetValidValue(_Phone, value, "Phone")
            _PhoneInitialized = True
            ReportPropertyChanged("Phone")
            OnPhoneChanged()
        End Set
    End Property
    
    Private _Phone As PhoneNumber 
    
    Private _PhoneInitialized As Boolean
    
    Private Partial Sub OnPhoneChanging(value As PhoneNumber)
    End Sub
    
    Private Partial Sub OnPhoneChanged()
    End Sub
    #End Region
    #Region "Navigation Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BooksAndAuthors", "PersonAddress", "Address")>
     Public Property Addresses() As EntityCollection(Of Address)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Address)("BooksAndAuthors.PersonAddress", "Address")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Address)("BooksAndAuthors.PersonAddress", "Address", value)
            End If
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BooksAndAuthors", "PersonBook", "Book")>
     Public Property Books() As EntityCollection(Of Book)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Book)("BooksAndAuthors.PersonBook", "Book")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Book)("BooksAndAuthors.PersonBook", "Book", value)
            End If
        End Set
    End Property
    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="BooksAndAuthors", Name:="SaleByMonth")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SaleByMonth 
    Inherits EntityObject
    #Region "Factory Method"
        
    ''' <summary>
    ''' Create a new SaleByMonth object.
    ''' </summary>
    ''' <param name="month">Initial value of the Month property.</param>
    ''' <param name="year">Initial value of the Year property.</param>
    ''' <param name="id">Initial value of the Id property.</param>
    ''' <param name="copiesSold">Initial value of the CopiesSold property.</param>
    Public Shared Function CreateSaleByMonth(month As Global.System.Int16, year As Global.System.Int16, id As Global.System.Int32, copiesSold As Global.System.Int64) As SaleByMonth
        Dim saleByMonth as SaleByMonth = New SaleByMonth
        saleByMonth.Month = month
            
        saleByMonth.Year = year
            
        saleByMonth.Id = id
            
        saleByMonth.CopiesSold = copiesSold
            
        Return saleByMonth
    End Function
    #End Region
    #Region "Primitive Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Month() As Global.System.Int16
        Get
            Return _Month
        End Get
        Set
            OnMonthChanging(value)
            ReportPropertyChanging("Month")
            _Month = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Month")
            OnMonthChanged()
        End Set
    End Property
    
    Private _Month as Global.System.Int16
    Private Partial Sub OnMonthChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnMonthChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Year() As Global.System.Int16
        Get
            Return _Year
        End Get
        Set
            OnYearChanging(value)
            ReportPropertyChanging("Year")
            _Year = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Year")
            OnYearChanged()
        End Set
    End Property
    
    Private _Year as Global.System.Int16
    Private Partial Sub OnYearChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnYearChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Id() As Global.System.Int32
        Get
            Return _Id
        End Get
        Set
            If (Id <> value) Then
                OnIdChanging(value)
                ReportPropertyChanging("Id")
                _Id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Id")
                OnIdChanged()
            End If
        End Set
    End Property
    
    Private _Id as Global.System.Int32
    Private Partial Sub OnIdChanging(value As Global.System.Int32)
    End Sub
    
    Private Partial Sub OnIdChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CopiesSold() As Global.System.Int64
        Get
            Return _CopiesSold
        End Get
        Set
            OnCopiesSoldChanging(value)
            ReportPropertyChanging("CopiesSold")
            _CopiesSold = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("CopiesSold")
            OnCopiesSoldChanged()
        End Set
    End Property
    
    Private _CopiesSold as Global.System.Int64
    Private Partial Sub OnCopiesSoldChanging(value As Global.System.Int64)
    End Sub
    
    Private Partial Sub OnCopiesSoldChanged()
    End Sub
    
    #End Region
    #Region "Navigation Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BooksAndAuthors", "BookSales", "Book")>
    Public Property Book() As Book
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Book)("BooksAndAuthors.BookSales", "Book").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Book)("BooksAndAuthors.BookSales", "Book").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property BookReference() As EntityReference(Of Book)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Book)("BooksAndAuthors.BookSales", "Book")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Book)("BooksAndAuthors.BookSales", "Book", value)
            End If
        End Set
    End Property
    #End Region
End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="BooksAndAuthors", Name:="Translator")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Translator 
    Inherits Person
    #Region "Factory Method"
        
    ''' <summary>
    ''' Create a new Translator object.
    ''' </summary>
    ''' <param name="sSN">Initial value of the SSN property.</param>
    ''' <param name="firstName">Initial value of the FirstName property.</param>
    ''' <param name="lastName">Initial value of the LastName property.</param>
    ''' <param name="phone">Initial value of the Phone property.</param>
    Public Shared Function CreateTranslator(sSN As Global.System.String, firstName As Global.System.String, lastName As Global.System.String, phone As PhoneNumber) As Translator
        Dim translator as Translator = New Translator
        translator.SSN = sSN
            
        translator.FirstName = firstName
            
        translator.LastName = lastName
            
        translator.Phone = StructuralObject.VerifyComplexObjectIsNotNull(phone, "Phone")
        Return translator
    End Function
    #End Region
    #Region "Navigation Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("BooksAndAuthors", "TranslatorLanguages", "Languages")>
     Public Property Languages() As EntityCollection(Of Language)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Language)("BooksAndAuthors.TranslatorLanguages", "Languages")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Language)("BooksAndAuthors.TranslatorLanguages", "Languages", value)
            End If
        End Set
    End Property
    #End Region
End Class

#End Region
#Region "ComplexTypes"
''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmComplexTypeAttribute(NamespaceName:="BooksAndAuthors", Name:="MonthOfYear")>
<DataContractAttribute(IsReference:=True)>
<Serializable()>
Public Partial Class MonthOfYear 
    Inherits ComplexObject
    #Region "Factory Method"
        
    ''' <summary>
    ''' Create a new MonthOfYear object.
    ''' </summary>
    ''' <param name="month">Initial value of the Month property.</param>
    Public Shared Function CreateMonthOfYear(month As Global.System.Int16) As MonthOfYear
        Dim monthOfYear as MonthOfYear = New MonthOfYear
        monthOfYear.Month = month
            
        Return monthOfYear
    End Function
    #End Region
    #Region "Primitive Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Month() As Global.System.Int16
        Get
            Return _Month
        End Get
        Set
            OnMonthChanging(value)
            ReportPropertyChanging("Month")
            _Month = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Month")
            OnMonthChanged()
        End Set
    End Property
    
    Private _Month as Global.System.Int16
    Private Partial Sub OnMonthChanging(value As Global.System.Int16)
    End Sub
    
    Private Partial Sub OnMonthChanged()
    End Sub
    
    #End Region
End Class

    
''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmComplexTypeAttribute(NamespaceName:="BooksAndAuthors", Name:="PhoneNumber")>
<DataContractAttribute(IsReference:=True)>
<Serializable()>
Public Partial Class PhoneNumber 
    Inherits ComplexObject
    #Region "Factory Method"
        
    ''' <summary>
    ''' Create a new PhoneNumber object.
    ''' </summary>
    ''' <param name="countryCode">Initial value of the CountryCode property.</param>
    ''' <param name="number">Initial value of the Number property.</param>
    Public Shared Function CreatePhoneNumber(countryCode As Global.System.String, number As Global.System.String) As PhoneNumber
        Dim phoneNumber as PhoneNumber = New PhoneNumber
        phoneNumber.CountryCode = countryCode
            
        phoneNumber.Number = number
            
        Return phoneNumber
    End Function
    #End Region
    #Region "Primitive Properties"
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property CountryCode() As Global.System.String
        Get
            Return _CountryCode
        End Get
        Set
            OnCountryCodeChanging(value)
            ReportPropertyChanging("CountryCode")
            _CountryCode = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("CountryCode")
            OnCountryCodeChanged()
        End Set
    End Property
    
    Private _CountryCode as Global.System.String
    Private Partial Sub OnCountryCodeChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnCountryCodeChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AreaCode() As Global.System.String
        Get
            Return _AreaCode
        End Get
        Set
            OnAreaCodeChanging(value)
            ReportPropertyChanging("AreaCode")
            _AreaCode = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("AreaCode")
            OnAreaCodeChanged()
        End Set
    End Property
    
    Private _AreaCode as Global.System.String = "1"
    Private Partial Sub OnAreaCodeChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnAreaCodeChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Number() As Global.System.String
        Get
            Return _Number
        End Get
        Set
            OnNumberChanging(value)
            ReportPropertyChanging("Number")
            _Number = StructuralObject.SetValidValue(value, False)
            ReportPropertyChanged("Number")
            OnNumberChanged()
        End Set
    End Property
    
    Private _Number as Global.System.String
    Private Partial Sub OnNumberChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnNumberChanged()
    End Sub
    
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Extension() As Global.System.String
        Get
            Return _Extension
        End Get
        Set
            OnExtensionChanging(value)
            ReportPropertyChanging("Extension")
            _Extension = StructuralObject.SetValidValue(value, True)
            ReportPropertyChanged("Extension")
            OnExtensionChanged()
        End Set
    End Property
    
    Private _Extension as Global.System.String
    Private Partial Sub OnExtensionChanging(value As Global.System.String)
    End Sub
    
    Private Partial Sub OnExtensionChanged()
    End Sub
    
    #End Region
End Class

    
#End Region

